services:
  - couchdb
rvm:
  - 1.9.3
  - 2.1.5
notifications:
  email: false
before_script:
  - "rm .ruby-version"
  - "test/travis/setup_couch.sh"
  - "mv test/config/couchdb.admin.yml config/couchdb.admin.yml"
  - "mv test/config/couchdb.yml config/couchdb.yml"
  - "bundle exec rake RAILS_ENV=test db:rotate"
  - "bundle exec rake RAILS_ENV=test db:migrate"
after_script:
  - "cat tmp/*.test*.log" # printing logs from the failed integration tests
bundler_args: --without development debug
